set nocompatible

call pathogen#infect()
set rtp+=~/.vim/ropevim

set ruler
syntax on

" Set encoding
set encoding=utf-8

set list listchars=tab:\ \ ,trail:·

" Searching
set nohlsearch
set incsearch
set ignorecase
set smartcase

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*
set wildignore+=*.pyc,*.doc,*.mp3,*.mp4,*.png,*.jpg,*.epub

" Friendlier mappings for saving and quitting
map <M-s> :w<CR>
imap <M-s> <esc>:w<cr>i
map <M-w> :q<CR>
imap <M-w> <esc>:q<cr>i

" Status bar
set laststatus=2

" Without setting this, ZoomWin restores windows in a way that causes
" equalalways behavior to be triggered the next time CommandT is used.
" This is likely a bludgeon to solve some other issue, but it works
set noequalalways

" NERDTree configuration
let NERDTreeIgnore=['\.pyc$', '\.rbc$', '\~$']

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

function s:setupWrapping()
  set wrap
  set wrapmargin=2
  set textwidth=72
endfunction

function s:setupMarkup()
  call s:setupWrapping()
  map <buffer> <Leader>p :Hammer<CR>
endfunction

" Thorfile, Rakefile, Vagrantfile and Gemfile are Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru}    set ft=ruby

" md, markdown, and mk are markdown and define buffer-local preview
au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn} call s:setupMarkup()

" add json syntax highlighting
au BufNewFile,BufRead *.json set ft=javascript

au BufRead,BufNewFile *.txt call s:setupWrapping()

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" load the plugin and indent settings for the detected filetype
filetype on
filetype plugin on
filetype indent on

" Opens an edit command with the path of the currently edited file filled in
" Normal mode: <Leader>e
map <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

" Opens a tab edit command with the path of the currently edited file filled in
" Normal mode: <Leader>t
map <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>

" Inserts the path of the currently edited file into a command
" Command mode: Ctrl+P
cmap <C-P> <C-R>=expand("%:p:h") . "/" <CR>

" gist-vim defaults
if has("mac")
  let g:gist_clip_command = 'pbcopy'
elseif has("unix")
  let g:gist_clip_command = 'xclip -selection clipboard'
endif
let g:gist_detect_filetype = 1
let g:gist_open_browser_after_post = 1

" Use modeline overrides
set modeline
set modelines=10

" Turn off jslint errors by default
let g:JSLintHighlightErrorLine = 0

" % to bounce from do to end etc.
runtime! macros/matchit.vim

" Show (partial) command in the status line
set showcmd

let g:NERDTreeShowBookmarks=1
let g:NERDTreeShowHidden=1
let g:NERDTreeChDirMode=2


" Turn off the stupid bell
set noerrorbells
set visualbell
set t_vb=

" Turn on line numbers
set number

" Hide invisible characters
set invlist

" Display as much of the last line as possible
set display+=lastline

" Turn on spellcheck
set spell

"Make the arrow and movement keys wrap around lines
set whichwrap+=<,>,h,l,[,]

" Ignore case in search by default
set ic
set smartcase
set textwidth=0
set wrap
set linebreak

" Tab settings
set tabstop=4
set softtabstop=4
set shiftwidth=4
" set textwidth=80
set smarttab
" set expandtab
" set nosmartindent

" Tell Vim to always use the system clipboard for yank, delete, and paste
set clipboard=unnamed

" Use f5 to 'refresh' the file
map <F5> :e %<cr>
imap <F5> <Esc>:e %<cr>

set noswapfile
set nobackup

" MRU Most recently used file configuration
let MRU_Max_Entries = 1000

function Outline()
	set ft=outline
endfunction

function EndOutline()
	filetype detect
endfunction

map <F2> :call Outline()<cr>
imap <F2> <Esc>:call Outline()<cr>a

map <S-F2> :call EndOutline()<cr>
imap <S-F2> <Esc>:call EndOutline()<cr>a

" Function to replace a block of python code with its own output
if has("python")
python << EOL
import vim, StringIO,sys
def PyExecReplace(line1,line2):
  r = vim.current.buffer.range(int(line1),int(line2))
  redirected = StringIO.StringIO()
  sys.stdout = redirected
  exec('\n'.join(r) + '\n')
  sys.stdout = sys.__stdout__
  output = redirected.getvalue().split('\n')
  r[:] = output[:-1] # the -1 is to remove the final blank line
  redirected.close()
EOL
command -range Pyer python PyExecReplace(<f-line1>,<f-line2>)
endif
" Convert outline format to LaTeX
command Texify !python $HOME/.vim/scripts/texify.py % 

noremap <C-left> :call PrevBuffer()<CR>
noremap <C-right> :call NextBuffer()<CR>

function NextBuffer()
	if &buftype!='nofile'
		bnext
	endif
endfunction

function PrevBuffer()
	if &buftype!='nofile'
		bprevious
	endif
endfunction


" Set leader to , (comma) for easier reaching
let mapleader = ","

" Fuzzyfinder customizations
" map <leader>f :FufFileWithCurrentBufferDir **/<C-M> 
" map <leader><leader> :FufBuffer<C-M>
" map <leader>mr :FufMruFile<C-M>
" map <leader>mm :FufMruFile<C-M>
" let g:fuf_modesDisable = ['mrucmd']


" Command T config
let g:CommandTScanDotDirectories=1
let g:CommandTMaxDepth=10
let g:CommandTMaxFiles=20000
" let g:CommandTMatchWindowAtTop=0
" let g:CommandTMaxHeight=10
" let g:CommandTMatchWindowReverse=1
" let g:CommandTMaxFiles=10000
" let g:CommandTMaxCachedDirectories=5


" Binding for nicer buffer closing
" map <M-w> <Plug>BufKillBd

if has("python")
" This is a nifty function for creating bulleted lists and other things. When
" you press shift-enter at the end of a line, it duplicates everything before
" the first letter or digit on that line onto the next line. 
python << endpython
import vim
import re
def list_newline():
	(row,col) = vim.current.window.cursor
	line = vim.current.buffer[row-1] 
	pattern = re.split(r'[a-zA-Z0-9]',line,1)[0]
	vim.current.buffer[row-1]+="\n"
	vim.current.buffer[row:row] = [pattern]
	vim.current.window.cursor = (row+1,len(pattern))
	vim.command('star!') # enter insert mode
endpython

imap <S-cr> <Esc>:python list_newline()<cr>
map <S-cr> :python list_newline()<cr>
endif

" Generate a handy tasklist
noremap <Leader>tl :noautocmd vimgrep /TODO/j %<CR>:cw<CR>

" MiniBuf Explorer configuration
let g:miniBufExplUseSingleClick = 0
let g:miniBufExplModSelTarget=1
" let g:miniBufExplorerMoreThanOne=3
let g:NERDTreeMouseMode = 2
let g:miniBufExplorerMoreThanOne = 10000

" Enable the mouse for things like xterm, etc.
if has("mouse")
	set mouse=a
endif

" Supertab configuration
let g:SuperTabDefaultCompletionType="context"
" set completeopt=longest,menuone,preview
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" MiniBufExplorer config
hi link MBEVisibleChangedActive Search

if !has("gui_running")
	set t_Co=256
	let g:solarized_termcolors=256
	let g:solarized_termtrans=1
	set background=dark
	color solarized
end

" Ctrlp configuration
let g:ctrlp_match_window_reversed = 0
let g:ctrlp_match_window_bottom = 0
let g:ctrlp_jump_to_buffer = 0
let g:ctrlp_mruf_max = 1000
let g:ctrlp_max_files = 3000
let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'
let g:ctrlp_max_depth = 10
let g:ctrlp_mruf_last_entered = 1
map <leader>f :CtrlP<CR>
map <leader><leader> :CtrlPMRU<CR>
" map <leader>mm :CtrlPMRU<CR>
let g:ctrlp_extensions = ['dir']
map <leader>. :CtrlPDir<CR>

" Faster window switching
map <M-j> :wincmd j<CR>
map <M-h> :wincmd h<CR>
map <M-k> :wincmd k<CR>
map <M-l> :wincmd l<CR>

" set statusline=%<%f\ %h%m%r\ %{fugitive#statusline()}\ %=%-14.(%l,%c%V%)\ %p%%

map <M-/> <plug>NERDCommenterToggle<CR>
imap <M-/> <Esc><plug>NERDCommenterToggle<CR>i

" Yankring mapping
nnoremap <silent> <leader>yr :YRShow<CR>

" Use j and k to navigate screen lines, not code lines (for very long lines)
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap <up> gk
nnoremap <down> gj
vnoremap <up> gj
vnoremap <down> gk

autocmd FileType python setlocal omnifunc=RopeCompleteFunc
let g:ropevim_enable_shortcuts = 0

map <leader>cd :execute "chdir ".escape(expand("%:p:h"), ' ')<CR>

if &diff
	set columns=210
endif

" OS-specific configurations:
if has("macunix")
	runtime config/macunix.vim
elseif has("gui_gnome")
	runtime config/gui_gnome.vim
elseif has("win32")
	runtime config/win32.vim
endif

